doorkeeper_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::DoorkeeperCleanupJob"
  queue: cleanup
  description: "Cleanup expired OAuth tokens"

notification_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::NotificationCleanupJob"
  queue: cleanup
  description: "Cleanup expired notifications"

spam_cleanup:
  cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
  class: "Scheduler::SpamCleanupJob"
  queue: cleanup
  description: "Cleanup spam contents before 1 month ago"

vlrgg_matches_service_job:
  cron: "* * * * *"
  class: "Scheduler::Vlrgg::MatchesServiceJob"
  queue: spider
  # args:
    # hard: "stuff"

vlrgg_player_stats_service_job:
  cron: "<%= Random.rand(0..59) %> * * * *"
  class: "Scheduler::Vlrgg::PlayerStatsServiceJob"
  queue: spider
  # args:
    # hard: "stuff"

vlrgg_team_rankings_service_job:
  cron: "<%= Random.rand(0..59) %> * * * *"
  class: "Scheduler::Vlrgg::TeamRankingsServiceJob"
  queue: spider
  # args:
    # hard: "stuff"

vlrgg_live_matches_service_job:
  cron: "* * * * *"
  class: "Scheduler::Vlrgg::LiveMatchesServiceJob"
  queue: spider

vlrgg_team_service_job:
  cron: "<%= Random.rand(0..59) %> * * * *"
  class: "Scheduler::Vlrgg::TeamServiceJob"
  queue: spider

vlrgg_events_service_job:
  cron: "<%= Random.rand(0..59) %> */2 * * *"
  class: "Scheduler::Vlrgg::EventsServiceJob"
  queue: spider

vlrgg_check_live_matches_job: # every 5th minute
  cron: "*/5 * * * *"
  class: "Scheduler::Vlrgg::CheckLiveMatchesJob"
  queue: spider
